# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 09:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2017, 1, 11, 9, 10, 11, 135871, tzinfo=utc))),
                ('company_added', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
